image: node:20
stages:
  - build
  - test

cache:
  paths:
    - node_modules/

before_script:
  - yarn install --frozen-lockfile

build_plugin:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - main.js
    expire_in: 1 hour

run_tests:
  stage: test
  script:
    - yarn coverage
  artifacts:
    reports:
      junit: coverage/junit.xml
    paths:
      - coverage/
    expire_in: 1 hour
